---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: proxmox-csi
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: proxmox-csi-plugin
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    # Reference to existing secret containing Proxmox config
    existingConfigSecret: proxmox-csi-secret
    existingConfigSecretKey: config.yaml

    # Node plugin configuration
    node:
      nodeSelector:
        node.cloudprovider.kubernetes.io/platform: nocloud
      tolerations:
        - operator: Exists

    # Controller configuration for Talos
    controller:
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          effect: NoSchedule

    # Storage class configuration
    storageClass:
      - name: local-lvm
        storage: data
        reclaimPolicy: Delete
        fstype: ext4
        ssd: true
        cache: writethrough
        extraParameters:
          csi.storage.k8s.io/node-stage-secret-name: "proxmox-csi-secret"
          csi.storage.k8s.io/node-stage-secret-namespace: "storage"
          csi.storage.k8s.io/node-expand-secret-name: "proxmox-csi-secret"
          csi.storage.k8s.io/node-expand-secret-namespace: "storage"
