---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrepository-source-v1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: snappass
spec:
  interval: 1h
  chart:
    spec:
      chart: ./charts/snappass
      sourceRef:
        kind: GitRepository
        name: snappass
        namespace: tools
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: cloudflare-tunnel
      namespace: network
  values: {}