# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:sBpEKrXA7UNspCSlQJWiHDPR1HsSqlNh9RoSbuEOwQEB5UGUCJUOZQ==,iv:Ry7G9vkRVX5QjUCH+dltiGvY6hiHw2ejiAjkp6Tm6Lc=,tag:9FiLRjiiB+3nBLZ+LYyE/Q==,type:str]
sops:
  age:
    - recipient: age16xcgc6qypft6p597t5sfzsfhmnja9378p53mzfmjmf0yeutx3elqyy8vyk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqQS9ZdGtMVUszS0Y5bCtw
        ZHg2QkRIVGxYQXdzMWQvMElEL2FteTl0a0dzCkh6SjFUR2ExdGxYSjF6OEVjWThm
        WmlYRGd2Z0tNclhSMnlJaUx0c0FudkEKLS0tIFVJclVsOVRxb1pLZ1lPcmMyd2RG
        VUs3dmdadUw1OTBRNDBFcnUrZUZOeGsKjjOuRu9Um/7ijTTJl2DmO5eUHNNYlShh
        GCOwTMPK6znLhWQVQ8Bt//7RJBc+lP2HAFl2kjduATjfypBeB+gFBw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-04T11:12:57Z"
  mac: ENC[AES256_GCM,data:aWxeaNMT0thxlXYoIfKFu0N5gaBxY8VaCO1AKwrReatzvdqbNHUhZiL9ulHOq2BMkc820h9xGjxzKCty+iCMCm9PkXACwAzSN7yPoqvgar1CDSaWbYbReFCk81vzIG38odKpV1qI71Dd71VdeQClvaPmOpvTUx9qgZI8MjmFLpc=,iv:mua30Fkcchwh9G7OK4PMMXNlrrRDDc8hqlojUmIPupE=,tag:t27ArG5u1J4n3lJ7XBEF5A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
