apiVersion: v1
kind: Secret
metadata:
  name: synology-csi-client-info
  namespace: storage
type: Opaque
stringData:
  client-info.yml: ENC[AES256_GCM,data:YxqqTQ4GLR8paFQvOB55J15UZy/+gqtIUlH9f5UA/dKyHTyhPlmVNfxkwbnMwVm2jn6nb/SMoGDOUCezxmY4lHkuFbKTetLsmhTYR2kdkVpSrhmmjZj932OLNbHV6D+qW+ZTd5L7IXOxN1A9Rg==,iv:p7GCmPrTevzE43o7lNS1LffIreICLVLEqfK5cdtqLCY=,tag:Io2DiLZlbT7PuapRD3iDGg==,type:str]
sops:
  age:
    - recipient: age16xcgc6qypft6p597t5sfzsfhmnja9378p53mzfmjmf0yeutx3elqyy8vyk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcjdXZXZTWDg2VjhlUlVt
        em5WOThNOGs5UTYzVnhLMmlCMTRicGg5ZUR3CmR5YUppWFgzMVZacU5TTjg1NDFE
        VzVqT01TQmNhV0tGb2JMYUdRbndKdXcKLS0tIExXK0FaN1hITzVkSm5JMGZ2azdS
        cTY5dklMTVR1NnBDeDZnOFhTaUhpcncKxtLYS52RZ74pvgq1PG74aTYlg3PcNRjZ
        pJGR8ud6YJTja1g+cG9fJXcvDq2xGybZQUKmS350ijduKWuR4EkOMw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-04T06:37:30Z"
  mac: ENC[AES256_GCM,data:EaAOPRPvVrJC9hxyPD5eVLaZMdvBwiHLKQVJ3T/VY7mh7jsb+pGNd/caI9f81VzvG7MlAia0wMBhB/tdbMFIizTQxIIVvkWg2O+HiaXKBDOqoYdHVqniEE/Rji8wjFVa3x8bMSvVIcGJwEpoyST/bm/mY36NnDL55jv60JhYrB0=,iv:mS3XH3bTdOy95LqEdtKqMQUqPIgBgmB8pk9r4dkrIUY=,tag:HsPEs0FEukEgoKJjGfmO3w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
